all:
	g++ source/main.cpp source/testtoolBind.cpp source/testtoolFunction.cpp source/testtoolMemberFunction.cpp source/testtoolRefWrapper.cpp -o unittest -I . -I ../../tool

.PHONY: clean

clean:
	rm -f unittest
